parameters:
#    perpustakaan_ansera.example.class: Perpustakaan\AnseraBundle\Example

services:
#    perpustakaan_ansera.example:
#        class: %perpustakaan_ansera.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
